"""start and complete item timestamps

Revision ID: 6b28936c8a95
Revises: 1cb2b2c7e767
Create Date: 2026-10-06 01:33:27.287223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b28936c8a95'
down_revision: Union[str, Sequence[str], None] = '1cb2b2c7e767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('started_at', sa.DateTime(timezone=True)))
    op.add_column('items', sa.Column('completed_at', sa.DateTime(timezone=True)))
    op.drop_column('items', 'completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('items', 'completed_at')
    op.drop_column('items', 'started_at')
    # ### end Alembic commands ###
