"""Item parent id added

Revision ID: b95d6d6db48a
Revises: 6b28936c8a95
Create Date: 2026-10-09 14:58:58.822874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b95d6d6db48a'
down_revision: Union[str, Sequence[str], None] = '6b28936c8a95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'items', 'items', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'parent_id')
    # ### end Alembic commands ###
